---
- hosts: controllers
  become_user: root
  become: true
  remote_user: root
  tasks:
  - name: make directory for Kubernetes
    file: path=/var/lib/kubernetes state=directory
  - name: make directory for provider configs
    file: path=/etc/kubernetes state=directory
  - name: make directory for kubelet config
    file: path=/var/lib/kubelet state=directory
  - name: upload CA certificate pem
    copy:
      src: ../output/ca.pem
      dest: /var/lib/kubernetes
      owner: root
      group: root
      mode: 0644
  - name: upload Kubernetes certificate pem
    copy:
      src: ../output/kubernetes.pem
      dest: /var/lib/kubernetes
      owner: root
      group: root
      mode: 0644
  - name: upload Kubernetes key pem
    copy:
      src: ../output/kubernetes-key.pem
      dest: /var/lib/kubernetes
      owner: root
      group: root
      mode: 0600
  - name: upload kube-apiserver systemd unit
    copy:
      src: ../templates/kube-apiserver.service
      dest: /etc/systemd/system
      owner: root
      group: root
      mode: 0600
  - name: upload kube-controller-manager systemd unit
    copy:
      src: ../templates/kube-controller-manager.service
      dest: /etc/systemd/system
      owner: root
      group: root
      mode: 0600
  - name: upload kube-scheduler systemd unit
    copy:
      src: ../templates/kube-scheduler.service
      dest: /etc/systemd/system
      owner: root
      group: root
      mode: 0600
  - name: upload start-kube-controller-manager.sh script
    copy:
      src: ../output/start-kube-controller-manager.sh
      dest: /usr/local/sbin
      owner: root
      group: root
      mode: 0500
  - name: upload start-kube-apiserver.sh script
    copy:
      src: ../output/start-kube-apiserver.sh
      dest: /usr/local/sbin
      owner: root
      group: root
      mode: 0500
  - name: upload start-kube-scheduler.sh script
    copy:
      src: ../scripts/start-kube-scheduler.sh
      dest: /usr/local/sbin
      owner: root
      group: root
      mode: 0500
  - name: upload token.csv
    copy:
      src: ../output/token.csv
      dest: /var/lib/kubernetes
      owner: root
      group: root
      mode: 0600
  - name: upload authorization-policy.jsonl
    copy:
      src: ../templates/authorization-policy.jsonl
      dest: /var/lib/kubernetes
      owner: root
      group: root
      mode: 0600
  - name: Force systemd to reread configs
    systemd: daemon_reload=yes
  - name: enable and start kube-apiserver
    systemd:
      name: kube-apiserver
      enabled: yes
      state: started
  - name: enable and start kube-controller-manager
    systemd:
      name: kube-controller-manager
      enabled: yes
      state: started
  - name: enable and start kube-scheduler
    systemd:
      name: kube-scheduler
      enabled: yes
      state: started
